### ISSUE TITLE
Physical interface

### ISSUE THREAD

**Issue by mickesskrp** [arkypita/ESP8266-SerialWebSocket#1]
Hi
I'm new with the LaserGrbl but the interface is up and running. Still waiting for som parts though so the engraver machine is not finished yet. 

I would like to add some physical interface to the GPIOs of the ESP8266 to add functions when your standing at the engraver. It could be pause/resume, jog, halt etc. My problem is that I haven't been able to figure out the correct way to send the G-codes through the websocket sketch. Is possible for you (or someone else...) to share information about this?

Thanks in advance
Mike

**Comment by arkypita** [comment]
Hi Mike
ESP8266 talk with grbl on your arduino via serial TX-RX line.

![image](https://user-images.githubusercontent.com/8782035/32266382-816cdd90-bee7-11e7-9f90-7281d965051f.png)

The required command for pause/resume/jog can be sent from ESP to Grbl are enumerated in this documentation: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands

You need to modify my [websocketserver.ino](https://github.com/arkypita/ESP8266-SerialWebSocket/blob/master/websocketserver/websocketserver.ino) ESP8266 sketch to read some buttons (is this what you mean with physical interface, right?) via its GPIO and send the desired command.

You can add a function in your loop like this:

```
void loop()
{
    term.loop();
    webSocket.loop();
    httpServer.handleClient();
    ManageGPIO();
}

void ManageGPIO()
{
    if (ButtonFrontUP(GPIO_BUTTON_PAUSE))     //PSEUDO CODE
         Serial.write('!'); //feed hold command, according to grbl documentation
}
```

Please note that Realtime commands can be sent as-is and does not need '\n' newline char.

Also note that Realtime commands does not give the "ok" feedback. This is very important because if LaserGRBL (or any other streamer) receive an unpredictable "ok" weird stuff can happens.
So if you need to send a command that give back an "ok" (like jogging, or $C, $X, $H) you must add a trap to strip-out the correspondent "ok" response and prevent sending to the streamer software on PC.

**Comment by arkypita** [comment]
You know that Grbl on arduino itself has some phisycal IO for some function (feed hold, resume, abort but not jog) that you can use directly adding a pushbutton to its pin?

![image](https://user-images.githubusercontent.com/8782035/32266867-6c571b8a-bee9-11e7-8f64-59e6c740e95c.png)

**Comment by mickesskrp** [comment]
Than you for your quick solution! 

I must have done something wrong in testing because now my ESP keeps disconnecting after 1-2 minutes. I've erased the flash and recompiled it with the original sketch but the result is just the same. Guess I'll just have to order some new ESPs... ;-)

**Comment by arkypita** [comment]
I have found this awesome board that is an arduino UNO + ESP8266 in the same board.
I really suggest it. If you buy with priority direct mail you have it in 1-2 week

https://www.banggood.com/it/UNOWiFi-R3-ATmega328PESP8266-Board-32Mb-Memory-USB-TTL-CH340G-Compatible-For-Arduino-Uno-p-1193957.html?rmmds=search&cur_warehouse=CN

**Comment by mickesskrp** [comment]
Thanks for the link. I've just placed an order...

**Comment by mickesskrp** [comment]
Is it possible to have the LaserGrbl recognize sent commands so that it updates the information, i.e. X/Y position when jogging via buttons connected to the ESP GPIO pins?

**Comment by arkypita** [comment]
LaserGRBL already do that. Position information and machine status (paused, running, jogging, alarm...) are update anyway.

**Comment by mickesskrp** [comment]
Thanks! Closing.
